[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[[redirects]]
  from = "/"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"
  [[redirects]]
from = "https"//zido.netlify.app"
to = "/"
status = 200
[[redirects]]
  from = "/"
  to = "/register"
  status = 200
  edge_handler = "filterRequests"